### ISSUE TITLE
Project Setup for All Group Members

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#10]
I have finished adding the starter project that includes a full fledged backend and working frontend. It will let you sign in and sign up. We need to get the app set up for everyone on their own machines. Please coordinate with me so I can help with this.

Please check off your name when you're up and running on your machine.
- [x] @please-review 
- [x] @xelaxon 
- [x] @cjy95

**Comment by cjy95** [comment]
I got it set up with mongo DB, visual studio code and I got into Eat4Wellness project.
currently working on login but it seems like our login part of our project is not working properly!
please take a look guys!

**Comment by CrypticSquirrel** [comment]
We fixed the issue with the login. We forgot about the .env file. Now it works. Well done @cjy95.

**Comment by please-review** [comment]
I am all set up!

**Comment by xelaxon** [comment]
Done, got it working
