### ISSUE TITLE
Landing Page UI

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#11]
We need a Landing Page for our application. This will be the main page a user gets redirected to when logging into their account. 

In our landing page we will need a navigation bar to get to: 
- Profile Section
- Food Lookup Section
- Food Diary Section

**Comment by cjy95** [comment]
completed!

**Comment by CrypticSquirrel** [comment]
@cjy95 , can you include a quick screenshot of how it looks right now? Thanks!

**Comment by cjy95** [comment]
![image](https://user-images.githubusercontent.com/61712821/101715984-793e4300-3a6a-11eb-86c6-e24e58a4ab3d.png)

**Comment by CrypticSquirrel** [comment]
Thanks! Looks great! 💯 🥇
