### ISSUE TITLE
New MongoDB Routes 

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#13]
We need to update our MongoDB routes and add some new routes:

1. Update our Users table routes to save additional information given to us from the Sign Up Page.
2. Add some MongoDB routes that will create and save Food Items and Meals.

**Comment by CrypticSquirrel** [comment]
We can split this up in multiple issues because this is a fair amount of work. However, I will be working with @xelaxon to complete everything so we might just elect to keep it just 1 issue.

**Comment by xelaxon** [comment]
Finished the routes for created, deleting, and editing food and logs, as well as signup and login functions.
