### ISSUE TITLE
Profile Section UI

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#15]
We need to add a page where the user can view his/her profile. Display relevant information on this page.

**Comment by please-review** [comment]
All done all done!!  Sorry forgot to close this out earlier 😬

<img width="1379" alt="Screen Shot 2020-12-13 at 10 53 15 PM" src="https://user-images.githubusercontent.com/72583810/102038748-0e587900-3d96-11eb-8678-524a0855f334.png">
