### ISSUE TITLE
Food Search Page UI

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#16]
We need to add a food search page. The user should be able to view a table of foods and be able to search through them.

**Comment by CrypticSquirrel** [comment]
@cjy95, I made some updates in #22. Please pull the changes in and continue your work on this issue.

**Comment by cjy95** [comment]
![image](https://user-images.githubusercontent.com/61712821/102025598-0af9c900-3d67-11eb-83c3-cb92f27cd5dd.png)

**Comment by cjy95** [comment]
added the food search and it is completed.
if we have time, we can throw in more information of food and lists of food.
