### ISSUE TITLE
Food History Page UI

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#17]
This page will have to contain all the recent meals that the user has logged as well as the ability to add new items.

**Comment by cjy95** [comment]
![image](https://user-images.githubusercontent.com/61712821/102025613-3381c300-3d67-11eb-98ed-2ad248045f1c.png)

**Comment by cjy95** [comment]
food history page UI has been done.
if we could throw in add/delete section to our history would be nice.
but it is done nice and well.
gg
