### ISSUE TITLE
Create an ERD (entity relationship diagram)

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#3]
We were instructed by the professor to have an ERD with this project. Please create one from lucidchart and then upload a pdf to our repository. 

Here is a starter project you may use: https://app.lucidchart.com/lucidchart/54261181-62f1-4926-843e-2b8690bf65e0/edit?shared=true

**Comment by xelaxon** [comment]
![DBMS ER diagram (UML notation)](https://user-images.githubusercontent.com/31707043/101653806-bcb69400-3a0d-11eb-8567-68081c91f1dc.png)

**Comment by xelaxon** [comment]
Updated my previous UML diagram with CRUD commands to meet the requirements as stated for the Use Case Diagram.

Double checked with Ed, seems good to us.

**Comment by CrypticSquirrel** [comment]
Well done.
