### ISSUE TITLE
Feasibility Study

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#6]
In this issue we should aim to answer the question if this project is possible and doable with the resources we have. We may use class discussions/meetings to answer this question. 

Please discuss these items below: 
- [x]  Project Description
- [x]  Market Analysis (aka. "Will our teacher give us an `A`)
- [x]  Technical Specifications
- [x]  Conclusion (aka. Aim of Project)

Please refer to [this site](https://www.projectpractical.com/steps-to-prepare-feasibility-study-report-for-software-development-project/) if you need help understanding a feasibility study.

**Comment by CrypticSquirrel** [comment]
### Description
This goal is to provide what this project is about and include any background data. 

Here is my proposal for a description:
> BetterFood is an application for members to track their diets and connect to coaches in order to help them achieve their dietary goals. This application is sponsored by and developed for Eat4Wellness, a fictional company made up by my teacher.

**Comment by CrypticSquirrel** [comment]
### Market Analysis

This stage of the feasibility study is to figure out our target audience and see how they are likely to react to our project. This should also state the goal of our project.

Our audience is Professor Mubita and our goal is to get an `A`. We will aim to attempt to accomplish this with clear issue tracking, documentations, and sweet looking UI.

**Comment by CrypticSquirrel** [comment]
### Technical Specifications

We will detail the technologies we will use and if we have experience with them in this step. 

We will use: 
- HTML will help us layout the pages.
- CSS & Bootstrap Framework will help us create a user interface.
- Javascript will help us communicate data from our frontend to our backend.
- Node.js will be used for our backend
- [mysqljs](https://github.com/mysqljs/mysql) will allow our node.js to communicate with our mysql database
- mysql for our database and we will set this up with the command line

We have someone on our team with experience on all these technologies and will be able to do this without too much blockers.

**Comment by CrypticSquirrel** [comment]
## Conclusion 

The main aim of this project is to develop software that will get an `A` on our CPTR-460 final project.

**Comment by CrypticSquirrel** [comment]
@xelaxon , @cjy95 , @please-review - please review my feasibility study and comment on anything relevant. 

If everything looks good just leave a thumbs up. Thanks!

**Comment by cjy95** [comment]
Please read through and familiarize with this guys!

**Comment by please-review** [comment]
looks good to me!

**Comment by CrypticSquirrel** [comment]
This issue has been reviewed by all group members and can be closed now. Thanks everyone!
