### ISSUE TITLE
Project Requirements

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#7]
We need to outline requirements for our project. This will be done in two parts: 
1. Overview 
    - We will need to create a wiki page that outlines each requirement for the application.

2. Issues
    - Each issue will have requirements for each task that has been done and will be viewable from our kanban board or from our closed issues page.

**Comment by CrypticSquirrel** [comment]
We have a [wiki page](https://github.com/CrypticSquirrel/Eat4Wellness/wiki/Requirement-Specifications) for our general requirements. 

Requirements for issues will be added as they are created.

**Comment by CrypticSquirrel** [comment]
@please-review @xelaxon @cjy95, please review and thumbs up (or comment) if everything looks good to you.

**Comment by xelaxon** [comment]
Looks good to me!

**Comment by please-review** [comment]
looks good

**Comment by CrypticSquirrel** [comment]
Excellent. We can now close this issue.
