### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#8]
We need a use case diagram for our project. Please create one using lucidchart. 

I would suggest using the use case diagram template from lucid chart. 
1. Once logged in go to [the templates page](https://lucid.app/documents#/templates)
2. Search `uml` in the search bar top right
3. Select the `Use Case Diagram` template on the first row far left.

Make it simple. Here is a [tutorial](https://www.geeksforgeeks.org/designing-use-cases-for-a-project/) to help you.

We will need: 
- Login / Sign Up Pages
- Profile / Edit Profile Pages
- CRUD (create, read, update, delete) on food items
- CRUD on meal record items
- Search food items by NAME
- Search meal records by DATE
- Compare two food items

**Comment by cjy95** [comment]
[Eat4wellness proj .pdf](https://github.com/CrypticSquirrel/Eat4Wellness/files/5614369/Eat4wellness.proj.pdf)

**Comment by cjy95** [comment]
This is the basic set up for CPTR 460 project, just need to checked

**Comment by CrypticSquirrel** [comment]
Thanks for the work you did. I think we need to include a system for looking up things in our database. It can be simple but see [this link](https://www.lucidchart.com/pages/uml-use-case-diagram) for inspiration. Let me know if you need additional help. 👍

**Comment by cjy95** [comment]
[Eat4wellness proj  (1).pdf](https://github.com/CrypticSquirrel/Eat4Wellness/files/5614454/Eat4wellness.proj.1.pdf)

**Comment by CrypticSquirrel** [comment]
I have included a image of the use case diagram @cjy95 did below: 

![eat4well](https://user-images.githubusercontent.com/26554691/101711035-b43b7900-3a60-11eb-814e-7d09d94c69d7.jpeg)
