### ISSUE TITLE
Login/Sign-Up Page UI 

### ISSUE THREAD

**Issue by CrypticSquirrel** [CrypticSquirrel/Eat4Wellness#9]
Once you have your development environment set up please go ahead and modify the login and sign up pages to make them look prettier. 

I would suggest using [Bootstrap](https://v5.getbootstrap.com/) as that's a very beginner friendly framework and you do not have to deal with much css that way.

[Here](https://www.youtube.com/watch?v=3ENJ_xd625s) is an excellent tutorial to help you get started.

**Comment by please-review** [comment]
I have completed the login page and sign up page
 
<img width="367" alt="Sign-up Page" src="https://user-images.githubusercontent.com/72583810/101828144-295d8b80-3aff-11eb-974e-edb71ea1f078.png">



<img width="1436" alt="Sign-in Page" src="https://user-images.githubusercontent.com/72583810/101764367-ff2fad80-3aad-11eb-89fd-c4c25cc4457e.png">

**Comment by CrypticSquirrel** [comment]
Great job @please-review ! Looks very nice. You definitely put a lot of effort into this.

**Comment by please-review** [comment]
Thank you @CrypticSquirrel I appreciate it! I definitely learned a lot and actually enjoyed it 😀
